apiVersion: v1
data:
  .dockerconfigjson: eyJhbGciOiJSUzI1NiIsImtpZCI6Iko5R0hJaExmVzAzcnVEem5VNmNhQWx0MFdGMUNfUmd3XzhnQkJOVDV5amsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJla3MtYWRtaW4tdG9rZW4tamhueHAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZWtzLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNzNlNDlhZTItOWMxZC00OWM5LTk4MzYtMTEzMGRjNGU4OTdlIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmVrcy1hZG1pbiJ9.cN6Eo11g0u3WrNUH4DnLI7b9qITVW1ml_uwTOcMXz8QjVQ5oMCpZIKsBNCtq7zz-83WQYNf8d_y_eSFdmmY9_22BhYrFlq9sN3OXlV_AmHCraquJc90QTiohLYHbF7d-ZFGQdzLgQalKDoycdwdCVBtsimSnjbPzXrRaKzAFm9RT_izlQdQRSQ4xAFSE04o0y-Rh2AP-r7VzrCq2soMhaHUQNu-lSXw8oYi23ogGGrv1tTge0P8_jF15txb4RmHQrqT3G_zzpZeRo_piVvUsiGrNg3odAQG0HcT3dmZCglb0_MTdu-EK-Khjmqhr3RcFOnwThxwUhHAOnoaSkCCaZQ
kind: Secret
metadata:
  creationTimestamp: null
  name: nexus-express-api
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: express-api
spec:
  selector:
    app: express-api
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: app
          image: 8082-nexus-sotjtgrs.solutions-demo.opsera.io/opsera-demo-nodejs-express-api:2
          ports:
            - containerPort: 3000
          imagePullPolicy: Always